In [20]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [21]:
path = "/content/gdrive/MyDrive/machine_learning/pertemuan10"

In [48]:
import math
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier

**Latihan 01**

In [23]:
df = pd.read_excel(path + '/praktikum_mandiri/data/latihan1.xlsx')
df

   No  suhu  angin    kelas
0   1    10      0   dingin
1   2    25      0    panas
2   3    15      5   dingin
3   4    20      3    panas
4   5    18      7   dingin
5   6    20     10  dingin
6   7    22      5    panas
7   8    24      6    panas

In [24]:
X = np.array([
    [10, 0],
    [25, 0],
    [15, 5],
    [20, 3],
    [18, 7],
    [20, 10],
    [22, 5],
    [24, 6]
])

In [25]:
y = np.array([0, 1, 0, 1, 0, 0, 1, 1])

In [26]:
x_test = np.array([[16, 3]])

In [27]:
def euclidean_distance(x1, x2):
    return math.sqrt((x1[0]-x2[0])**2 + (x1[1]-x2[1])**2)

In [28]:
distances = []
for i in range(len(X)):
    dist = euclidean_distance(x_test[0], X[i])
    distances.append((dist, y[i]))

In [29]:
distances.sort(key=lambda x: x[0])

In [30]:
print("=== Hasil Perhitungan Jarak Manual ===")
for i, (d, label) in enumerate(distances):
    print(f"{i+1}. Jarak: {d:.3f} -> Kelas: {'Panas' if label else 'Dingin'}")

=== Hasil Perhitungan Jarak Manual ===
1. Jarak: 2.236 -> Kelas: Dingin
2. Jarak: 4.000 -> Kelas: Panas
3. Jarak: 4.472 -> Kelas: Dingin
4. Jarak: 6.325 -> Kelas: Panas
5. Jarak: 6.708 -> Kelas: Dingin
6. Jarak: 8.062 -> Kelas: Dingin
7. Jarak: 8.544 -> Kelas: Panas
8. Jarak: 9.487 -> Kelas: Panas

In [31]:
Ks = [1, 3, 5, 7]

In [32]:
print("\n=== Prediksi KNN Menggunakan Scikit-Learn ===")
for k in Ks:
    # Membuat model KNN dengan jumlah tetangga K
    knn = KNeighborsClassifier(n_neighbors=k)

    # Training model menggunakan data training
    knn.fit(X, y)

    # Prediksi kelas untuk data test
    prediction = knn.predict(x_test)[0]

    print(f"K = {k} -> Prediksi: {'Panas' if prediction else 'Dingin'}")

=== Prediksi KNN Menggunakan Scikit-Learn ===
K = 1 -> Prediksi: Dingin
K = 3 -> Prediksi: Dingin
K = 5 -> Prediksi: Dingin
K = 7 -> Prediksi: Dingin

**Latihan 02**

In [33]:
df_2 = pd.read_excel(path + '/praktikum_mandiri/data/latihan2.xlsx')
df_2

     NIM Hasil Sebenarnya Hasil Prediksi
0  TI001            Lulus          Lulus
1  TI002            Lulus          Lulus
2  TI003            Lulus          Lulus
3  TI004            Lulus    Tidak Lulus
4  TI005            Lulus    Tidak Lulus
5  TI006      Tidak Lulus          Lulus
6  TI007      Tidak Lulus    Tidak Lulus
7  TI008      Tidak Lulus    Tidak Lulus
8  TI009      Tidak Lulus    Tidak Lulus
9  TI010      Tidak Lulus    Tidak Lulus

In [35]:
y_true = df_2['Hasil Sebenarnya']
y_pred = df_2['Hasil Prediksi']

In [36]:
cm = confusion_matrix(y_true, y_pred, labels=['Lulus', 'Tidak Lulus'])

In [40]:
accuracy = accuracy_score(y_true, y_pred)
precision = precision_score(y_true, y_pred, pos_label='Lulus')
recall = recall_score(y_true, y_pred, pos_label='Lulus')
f1 = f1_score(y_true, y_pred, pos_label='Lulus')

In [41]:
print("=== Evaluasi Model Prediksi Kelulusan ===")
print("Confusion Matrix:")
print(cm)
print("\nAccuracy:", round(accuracy, 2))
print("Precision:", round(precision, 2))
print("Recall:", round(recall, 2))
print("F1-Score:", round(f1, 2))

=== Evaluasi Model Prediksi Kelulusan ===
Confusion Matrix:
[[3 2]
 [1 4]]

Accuracy: 0.7
Precision: 0.75
Recall: 0.6
F1-Score: 0.67

**Latihan 03**

In [42]:
df_3 = pd.read_excel(path + '/praktikum_mandiri/data/latihan3.xlsx')
df_3

,Temperature,Humidity,Wind Speed,Precipitation(%),Cloud Cover,Atmospheric Pressure,UV Index
0,14.0,73,9.5,82.0,partly cloudly,1010.82,2
1,39.0,96,8.5,71.0,partly cloudly,1011.43,7
2,30.0,64,7.0,16.0,clear,1018.72,5
3,38.0,83,1.5,82.0,clear,1026.25,7
4,27.0,74,17.0,66.0,overcast,990.67,1
5,32.0,55,3.5,26.0,overcast,1010.03,2
6,-2.0,97,8.0,86.0,overcast,990.87,1
7,3.0,85,6.0,96.0,partly cloudly,984.46,1
8,3.0,83,6.0,66.0,overcast,999.44,0
9,28.0,74,8.5,107.0,clear,1012.13,8

In [50]:
X = df_3[['Temperature', 'Humidity', 'Wind Speed', 'Precipitation(%)', 'Atmospheric Pressure', 'UV Index']]
y_test= df_3['Cloud Cover']

In [51]:
encoder = LabelEncoder()
y = encoder.fit_transform(y_test)

In [52]:
print("Pemetaan Label Target:")
for i, label in enumerate(encoder.classes_):
    print(f"{label}: {i}")

Pemetaan Label Target:
clear: 0
overcast: 1
partly cloudly: 2

In [53]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
    )

In [55]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("\nBentuk data latih (X_train):", X_train_scaled.shape)
print("Bentuk data uji (X_test):", X_test_scaled.shape)

Bentuk data latih (X_train): (7, 6)
Bentuk data uji (X_test): (3, 6)

In [60]:
k = 5
knn_model = KNeighborsClassifier(n_neighbors=k)

knn_model.fit(X_train_scaled, y_train)

print(f"\nModel KNN dengan K={k} telah dilatih.")

Model KNN dengan K=5 telah dilatih.

In [61]:
y_pred = knn_model.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
print(f"\n--- Hasil Evaluasi Model (K={k}) ---")
print(f"Akurasi Model: {accuracy*100:.2f}%")

# 3. Tampilkan Laporan Klasifikasi
print("\nLaporan Klasifikasi:")
# Target names adalah label asli (partly cloudy, clear, overcast)
target_names = encoder.classes_
print(classification_report(y_test, y_pred, target_names=target_names))

--- Hasil Evaluasi Model (K=5) ---
Akurasi Model: 66.67%

Laporan Klasifikasi:
                precision    recall  f1-score   support

         clear       1.00      1.00      1.00         1
      overcast       0.50      1.00      0.67         1
partly cloudly       0.00      0.00      0.00         1

      accuracy                           0.67         3
     macro avg       0.50      0.67      0.56         3
  weighted avg       0.50      0.67      0.56         3

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))